add pre-commit

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -3,7 +3,7 @@ name: Docker Image CI
 on:
   push:
     tags:
-      - 'v*'
+      - "v*"
 
 permissions:
   contents: read
@@ -14,113 +14,113 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check out the repository
-      uses: actions/checkout@v4
+      - name: Check out the repository
+        uses: actions/checkout@v4
 
-    - name: Extract version from tag (remove 'v')
-      id: get_version
-      run: |
-        VERSION=${GITHUB_REF##*/}
-        VERSION=$(echo $VERSION | sed 's/^v//')
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - name: Extract version from tag (remove 'v')
+        id: get_version
+        run: |
+          VERSION=${GITHUB_REF##*/}
+          VERSION=$(echo $VERSION | sed 's/^v//')
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    - name: Build the Docker image
-      run: docker build --build-arg VELOCITY_VERSION=$VERSION -t endkind/velocity:$VERSION .
+      - name: Build the Docker image
+        run: docker build --build-arg VELOCITY_VERSION=$VERSION -t endkind/velocity:$VERSION .
 
-    - name: Save Docker image for test job
-      run: docker save endkind/velocity:$VERSION > image.tar
+      - name: Save Docker image for test job
+        run: docker save endkind/velocity:$VERSION > image.tar
 
-    - name: Upload image artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: docker-image
-        path: image.tar
+      - name: Upload image artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-image
+          path: image.tar
 
   test:
     runs-on: ubuntu-latest
     needs: build
 
     steps:
-    - name: Check out the repository
-      uses: actions/checkout@v4
+      - name: Check out the repository
+        uses: actions/checkout@v4
 
-    - name: Download image artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: docker-image
+      - name: Download image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-image
 
-    - name: Extract version from tag (remove 'v')
-      id: get_version
-      run: |
-        VERSION=${GITHUB_REF##*/}
-        VERSION=$(echo $VERSION | sed 's/^v//')
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - name: Extract version from tag (remove 'v')
+        id: get_version
+        run: |
+          VERSION=${GITHUB_REF##*/}
+          VERSION=$(echo $VERSION | sed 's/^v//')
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    - name: Determine port
-      id: determine-port
-      run: |
-        if [[ "$VERSION" =~ ^(3\.2\.0-SNAPSHOT|3\.1\.2-SNAPSHOT|3\.1\.1-SNAPSHOT|3\.1\.1|3\.1\.0|1\.1\.9|1\.0\.10)$ ]]; then
-          echo "PORT=25577" >> $GITHUB_ENV
-        else
-          echo "PORT=25565" >> $GITHUB_ENV
-        fi
+      - name: Determine port
+        id: determine-port
+        run: |
+          if [[ "$VERSION" =~ ^(3\.2\.0-SNAPSHOT|3\.1\.2-SNAPSHOT|3\.1\.1-SNAPSHOT|3\.1\.1|3\.1\.0|1\.1\.9|1\.0\.10)$ ]]; then
+            echo "PORT=25577" >> $GITHUB_ENV
+          else
+            echo "PORT=25565" >> $GITHUB_ENV
+          fi
 
-    - name: Load Docker image
-      run: docker load < image.tar
+      - name: Load Docker image
+        run: docker load < image.tar
 
-    - name: Prepare Test
-      run: |
-        python -m venv .venv
-        source .venv/bin/activate
-        pip install -r .github/requirements.txt
+      - name: Prepare Test
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install -r .github/scripts/requirements_test.txt
 
-    - name: Test the Docker image
-      run: |
-        # Start the container
-        CONTAINER_ID=$(docker run -it -d -p 25565:$PORT endkind/velocity:$VERSION)
+      - name: Test the Docker image
+        run: |
+          # Start the container
+          CONTAINER_ID=$(docker run -it -d -p 25565:$PORT endkind/velocity:$VERSION)
 
-        # Wait for the container to initialize and check the port from the host
-        MAX_RETRIES=60
-        RETRY_COUNT=0
-        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
-          # Check if the container is running
-          if [ "$(docker ps -q -f id=$CONTAINER_ID)" == "" ]; then
-            echo "Container failed to start."
+          # Wait for the container to initialize and check the port from the host
+          MAX_RETRIES=60
+          RETRY_COUNT=0
+          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+            # Check if the container is running
+            if [ "$(docker ps -q -f id=$CONTAINER_ID)" == "" ]; then
+              echo "Container failed to start."
+              exit 1
+            fi
+
+            # Check if port 25565 is open
+            if .venv/bin/python .github/scripts/test.py; then
+              echo "Port 25565 is open and accessible from the host."
+              break
+            fi
+
+            # Increment retry count and wait
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+            echo "Waiting for container to initialize... ($RETRY_COUNT/$MAX_RETRIES)"
+            sleep 5
+          done
+
+          # If the container still isn't ready, fail the job
+          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+            echo "Container did not initialize within the expected time."
+            docker logs $CONTAINER_ID
+            docker stop $CONTAINER_ID
+            docker rm $CONTAINER_ID
             exit 1
           fi
 
-          # Check if port 25565 is open
-          if .venv/bin/python .github/test.py; then
-            echo "Port 25565 is open and accessible from the host."
-            break
-          fi
-
-          # Increment retry count and wait
-          RETRY_COUNT=$((RETRY_COUNT + 1))
-          echo "Waiting for container to initialize... ($RETRY_COUNT/$MAX_RETRIES)"
-          sleep 5
-        done
-
-        # If the container still isn't ready, fail the job
-        if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
-          echo "Container did not initialize within the expected time."
-          docker logs $CONTAINER_ID
           docker stop $CONTAINER_ID
-          docker rm $CONTAINER_ID
-          exit 1
-        fi
+          docker logs $CONTAINER_ID > docker.log
 
-        docker stop $CONTAINER_ID
-        docker logs $CONTAINER_ID > docker.log
-
-    - name: Upload log artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: docker-log
-        path: docker.log
+      - name: Upload log artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-log
+          path: docker.log
 
   push:
     runs-on: ubuntu-latest
@@ -129,29 +129,29 @@ jobs:
       - test
 
     steps:
-    - name: Check out the repository
-      uses: actions/checkout@v4
+      - name: Check out the repository
+        uses: actions/checkout@v4
 
-    - name: Download image artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: docker-image
+      - name: Download image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-image
 
-    - name: Extract version from tag (remove 'v')
-      id: get_version
-      run: |
-        VERSION=${GITHUB_REF##*/}
-        VERSION=$(echo $VERSION | sed 's/^v//')
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - name: Extract version from tag (remove 'v')
+        id: get_version
+        run: |
+          VERSION=${GITHUB_REF##*/}
+          VERSION=$(echo $VERSION | sed 's/^v//')
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    - name: Load Docker image
-      run: docker load < image.tar
+      - name: Load Docker image
+        run: docker load < image.tar
 
-    - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    - name: Push the Docker image
-      run: docker push endkind/velocity:$VERSION
+      - name: Push the Docker image
+        run: docker push endkind/velocity:$VERSION
 
   create-issue-on-failure:
     runs-on: ubuntu-latest
@@ -188,4 +188,3 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           filename: .github/ISSUE_TEMPLATE.md
-
